### ISSUE TITLE
[Features request]

### ISSUE THREAD

**Issue by luckcolors** [peterhellberg/tpb-search#2]
Hello i really like the tpb search app.
I'm asking if you could add those 2 features to the app.
Feature 1 : function to continue indexing from the last run
Feature 2 : support of other database engines for the indexed DB (i'm asking this because from an 420mb csv i get 2gb/more of indexed DB)
Thanks in advance :)

**Comment by luckcolors** [comment]
For the db type i found this : https://github.com/blevesearch/bleve/tree/master/index/store
Also it seems that the database it's using now is BoltDb 
(i know this because inside the rbp.index folder there's an json : {"storage":"boltdb"} )
mayby it's possible to create an config for using an different DB.

**Comment by peterhellberg** [comment]
Ah, I’ll look into it :) Thanks

On Thursday, January 1, 2015, luckcolors <notifications@github.com> wrote:

> For the db type i found this :
> https://github.com/blevesearch/bleve/tree/master/index/store
> Also it seems that the database it's using now is BoltDb
> (i know this because inside the rbp.index folder there's an json :
> {"storage":"boltdb"} )
> mayby it's possible to create an config for using an different DB.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterhellberg/tpb-search/issues/2#issuecomment-68487553>
> .
>


-- 

--
Peter Hellberg
Ruby Developer, Code7 Interactive

**Comment by peterhellberg** [comment]
@luckcolors I’ve found an easy way to use LevelDB instead of BoltDB:

Install the `github.com/jmhodges/levigo` package and then build tpb-search with `-tags leveldb`

**Comment by peterhellberg** [comment]
Indexing time with LevelDB seems to be much more linear with an average of 0.48ms/doc on my laptop.

I’m considering just switching to using LevelDB by default, but that would mean that you couldn’t just go get tpb-search anymore (Since LevelDB isn’t written in Go)

**Comment by luckcolors** [comment]
could you please provide me the Levigo Pkg prebuilt? i'm not able to build it on windows.

**Comment by peterhellberg** [comment]
I just indexed the entire `torrents_mini.csv.gz` using LevelDB:

``` bash
Finished indexing 7800260 documents in 7917.98s (average 1.02ms/doc)
```

The final index size:

``` bash
$ du -hs tpb.index
12G tpb.index
```

**Comment by luckcolors** [comment]
ok good to see. :)
anyway i'm not able to build the levelDB under windows....

**Comment by luckcolors** [comment]
I'm not able to build the application cause i use windows and leveldb has problems working on windows.
how can i build it with forestdb?
